version: '3.8'
services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb
    hostname: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      # MONGO_INITDB_DATABASE: videoGames
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
networks:
  main: